### ISSUE TITLE
Strings are not HTML escaped when rendered

### ISSUE THREAD

**Issue by Foslock** [warfares/pretty-json#16]
The text within a string leaf value is not HTML escaped when rendered, which leaves this open to scripting attacks, and minor UI failures like so:

```json
{
    "name": "John Doe <email@email.com>"
}
```

Which renders to:

```
{
name :  "John Doe "
}
```

One could also do something malicious like:

```json
{
    "name": "John Doe <script>alert('I am bad!')</script>"
}
```

Which will execute the arbitrary script. This can be fixed simply by changing the Leaf underscore template  to escape the data with a `<%-data%><` instead of `<%=data%>`.

**Comment by Foslock** [comment]
I have a change ready and tested, but no permissions to create a side branch?

**Comment by warfares** [comment]
Hey Thanks very much .. That make sense.

I'm in holidays now ... back Monday to work and I'll take a look.

Thanks,
Rodolfo

**Comment by warfares** [comment]
committed ... thanks.
